### PR TITLE
Typing notifications

### PR DESCRIPTION
**Pull request by LuccoJ**
This branch adds both incoming and outgoing typing notifications (Telepathy provides several states, but only INACTIVE and COMPOSING are used).
It also contains the changes from the UDP branch because I don't understand Git.
One thing I'm not too sure about is whether the Tox callback registration for the typing state is in the right place (src/textchannel.vala).

### CODE REVIEW

**Comment by abderrahim** [comment]
You should start a new branch using `git checkout -b branch_name master` so it doesn't contain your work from the other branch.

Anyway, it looks fine. I'll push it as soon as I test it.

**Comment by abderrahim** [comment]
I've pushed the outgoing notifications patch, but incoming notifications didn't work.

Looking closer at the patch I see two problems : first, tox friend numbers aren't the same as telepathy handles (there should be a comment on how to convert between the two); second, toxcore allows to register only one callback per type, so we cannot register a callback per channel (it should be registered in the connection like the other callbacks).

Thanks for your contribution.

**Comment by LuccoJ** [comment]
Thanks for having a look! It was working for me, but I had only tested it in very limited circumstance (i.e. only one online contact). I might have fixed it now: for the first issue, I'm now using target_handle instead of friend_number, which I believe is the relevant Telepathy number, while for the second issue, my solution was a bit convoluted (maybe there's a simple way but I obviously don't know Vala): since I couldn't reference a non-static method from the uninitialized class TextChannel in connection.vala, I made it register the method from the first instantiated channel that gets created, then I added a static boolean to ensure it wouldn't get re-registered on opening of more channels.

I'm going to test it with more than one contact (myself)... if I can convince any of the people I know to get Tox, which has failed so far.

**Comment by LuccoJ** [comment]
I think you can give it another try, I've talked to a friend on Tox while also having another online contact, and typing notifications were working both ways with the new code.

**Comment by abderrahim** [comment]
Sorry it took me so long to respond. I've reworked your patch a bit since it was assuming there would be only one channel.

Anyway, thank you for your contributions :+1:

**Comment by LuccoJ** [comment]
I thought just registering the callback when the first channel got created would be enough, and I didn't know how else to register a callback that was in a different class.
I see what you've done instead, though... the initial callback is in connection.vala and it takes care of finding out the right channel, and then delegates the actual work to it.

**Pull request closed without merging**
